# Generated by Django 3.2.16 on 2023-01-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_friend_followed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='followed_by',
        ),
    ]
